# image: "debian:stretch"
stages:
  - default
  - build
  - test

default-job:
  stage: default
  before_script:
    - echo "init the git submodule"
    - git submodule sync
    - git submodule update --init

build-job:
  stage: build
  script:
    - echo "start building..."
    - echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian bullseye main" >> /etc/apt/sources.list
    - apt-get update
    - apt-get install -y make cmake g++
    - mkdir build
    - cd build
    - cmake ..
    - make

test-job:
  stage: test
  script:
    - echo "test starts"
    - make test
