# image: "tico/docker:latest"
# image: "debian:stretch"
image: "debian:bullseye"


before_script:
  - echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian bullseye main" > /etc/apt/sources.list &&
    echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian bullseye-updates main" >> /etc/apt/sources.list
  - apt-get update
  - env DEBIAN_FRONTEND=noninteractive apt-get install -y make cmake g++ git
  
  - cp .gitmodules-ci .gitmodules # path issue
  - echo "init the git submodule"
  - git submodule sync
  - git submodule update --init


stages:
  - build
  - test


build-job:
  tags:
    - taag
  stage: build
  script:
    - echo "start building..."
    - mkdir build
    - cd build
    - cmake ..
    - make
    - pwd


test-job:
  tags:
    - taag
  stage: test
  script:
    - pwd
    - echo "test starts"
    - cd build
    - pwd
    - make test
